"""Role exclusions shared by the notifier and personalized catalogue matching."""

from __future__ import annotations

import html
import re
import unicodedata
from typing import Any


def _text(value: Any) -> str:
    text = unicodedata.normalize("NFKC", html.unescape(str(value or ""))).casefold()
    text = re.sub(r"<[^>]+>", " ", text)
    text = re.sub(r"[‐‑‒–—−]", "-", text)
    text = re.sub(r"\bp\s*\.?\s*h\s*\.?\s*d\b\.?", "phd", text)
    text = re.sub(r"\bpost[ -]+doc(?:toral)?\b", "postdoctoral", text)
    text = re.sub(r"\bpre[ -]+doctoral\b", "predoctoral", text)
    return re.sub(r"\s+", " ", text).strip()


_DOCTORAL_ROLE = re.compile(
    r"\b(?:phd|doctoral|doctorate|dphil|predoctoral)[ -]+"
    r"(?:research )?(?:students?|candidates?|researchers?|assistants?|fellows?|fellowships?|positions?|"
    r"scholarships?|studentships?|programmes?|programs?|projects?|training|opportunities)\b"
    r"|\b(?:students?|candidates?|positions?|studentships?) (?:for (?:a )?|in (?:a )?)?phd\b"
    r"|\b(?:studentships?|doktorand\w*|doktorant\w*)\b"
)


def doctoral_training_reason(job: dict[str, Any]) -> str | None:
    """Identify doctoral study, without treating an existing PhD as a disqualifier."""
    title = _text(job.get("title"))
    description = _text(job.get("description"))
    if _DOCTORAL_ROLE.search(title) or re.search(
        r"\b(?:phd|doctorate|dphil) (?:in|on)\b"
        r"|^(?:\d+ |fully funded |funded )?(?:phd|doctorate|dphil)\s*(?:[:/]|-\s|\([fmwd/ -]+\)|$)",
        title,
    ):
        return "doctoral training position"

    # Descriptions often disclose the degree programme behind a generic Research
    # Assistant title. Require recruitment/enrolment language, not just a mention
    # of a PhD, student supervision, or an institutional graduate programme.
    for sentence in re.split(r"[.!?;]", description):
        if re.search(
            r"\b(?:you|applicants?|candidates?|the successful (?:candidate|applicant)) "
            r"(?:will|must|would|are expected to) "
            r"(?:be (?:required to |expected to )?)?"
            r"(?:enrol\w* (?:in|on|for)|register\w* (?:in|for)|pursue|undertake|work towards?) "
            r"(?:an? |the )?(?:phd|doctorate|doctoral (?:degree|programme|program))\b",
            sentence,
        ):
            return "position requires doctoral enrolment"
        if re.search(
            r"\b(?:this|the) (?:position|role|post|project) "
            r"(?:is|offers|involves) (?:an? |the )?"
            r"(?:fully funded |funded )?(?:phd|doctoral|doctorate)\b",
            sentence,
        ):
            return "doctoral training position in description"
        if re.search(
            r"\b(?:we (?:are (?:seeking|recruiting|looking for)|seek|invite applications for|offer)|"
            r"applications are invited for) (?:an? |the )?(?:fully funded |funded )?"
            r"(?:phd|doctoral|predoctoral)[ -]+(?:student|candidate|researcher|fellow|position|scholarship)\b",
            sentence,
        ):
            return "doctoral recruitment in description"
    return None


_COMPUTATIONAL = re.compile(
    r"\b(?:computational|theoretical|in silico|bioinformatics|cheminformatics|"
    r"simulation\w*|modelling|modeling|scientific (?:computing|software)|"
    r"research software|molecular dynamics|density functional theory|quantum chemistry|"
    r"electronic structure|machine learning|data scien\w*|hpc|dft|qm/mm)\b"
)
_EXPERIMENTAL_METHODS = re.compile(
    r"\b(?:wet[ -]lab|bench[ -](?:work|science)|cell cultur\w*|protein purif\w*|"
    r"protein expression|organic synthesis|chemical synthesis|synthetic chemistry|"
    r"flow cytometry|microscopy|cryo[ -]?em|mass spectrometry|"
    r"assay (?:development|design)|develop\w* (?:\w+ )?assays|"
    r"animal (?:handling|experiments)|in vivo experiments|patch clamp|"
    r"electrophysiology|fabrication|experimental (?:measurements|characteri[sz]ation))\b"
)
_NEGATED_EXPERIMENTS = re.compile(
    r"\b(?:no|without) (?:\w+[ -]){0,3}(?:experiments?|experimental|wet[ -]lab|bench)\b"
    r"|\bnot (?:a |an |primarily |mainly )?(?:experimental|wet[ -]lab|bench)\b"
)
_COLLABORATION = re.compile(
    r"\b(?:collaborat\w*|experimental collaborators?|partner\w*|other teams?|"
    r"colleagues|provided by|generated by)\b"
)
_OWN_WORK = re.compile(
    r"\b(?:you (?:will|would)|responsibilities|duties|(?:role|position|work) involves|"
    r"conduct\w*|perform\w*|carry out|hands[ -]on|experience (?:in|with)|"
    r"expertise (?:in|with))\b"
)
_DATA_ANALYSIS = re.compile(
    r"\b(?:analy[sz]\w*|model\w*|process\w*|interpret\w*)\b[^.;]*\b(?:data|images|spectra|datasets)\b"
    r"|\b(?:data|image|spectral) analysis\b"
    r"|\bcompar\w*\b[^.;]*\b(?:simulations?|predictions?|models?)\b"
)
_DIRECT_EXPERIMENTS = re.compile(
    r"\b(?:perform\w*|conduct\w*|carry out|hands[ -]on) (?:\w+ ){0,2}"
    + _EXPERIMENTAL_METHODS.pattern
)


def experimental_role_reason(job: dict[str, Any]) -> str | None:
    """Reject experimental duties, but retain computational work with lab partners."""
    title = _text(job.get("title"))
    description = _text(job.get("description"))
    computational_title = bool(_COMPUTATIONAL.search(title) or _DATA_ANALYSIS.search(title))
    if not computational_title and (
        re.search(r"\b(?:experimental\w*|wet[ -]lab|bench scientist|synthetic chemist)\b", title)
        or _EXPERIMENTAL_METHODS.search(title)
    ):
        return "experimental or wet-lab title"

    # Split at contrast words as well as sentences so that lab collaborators in
    # one clause cannot hide the applicant's experimental duties in another.
    clauses = re.split(r"[.!?;]|\b(?:but|while|whereas)\b", description)
    experimental_hits: set[str] = set()
    computational_duties = computational_title
    for clause in clauses:
        if _NEGATED_EXPERIMENTS.search(clause):
            continue
        own_parts = [
            _COLLABORATION.split(part, maxsplit=1)[0]
            for part in re.split(r",|\band\b", clause)
        ]
        if any(re.search(
            r"\b(?:primarily|predominantly|mainly|largely) (?:an? )?"
            r"(?:experimental|wet[ -]lab|bench[ -]based)\b"
            r"|\b(?:wet[ -]lab|bench[ -]based) (?:role|position)\b",
            part,
        ) for part in own_parts):
            return "primarily experimental or wet-lab duties"

        methods = _EXPERIMENTAL_METHODS.findall(clause)
        if methods and _OWN_WORK.search(clause):
            # Explicit applicant duties take precedence over incidental mention
            # of computational collaborators or software elsewhere in the ad.
            if any(
                _OWN_WORK.search(part)
                and _EXPERIMENTAL_METHODS.search(part)
                and (not _DATA_ANALYSIS.search(part) or _DIRECT_EXPERIMENTS.search(part))
                for part in own_parts
            ):
                return "hands-on experimental duties"
        if not _COLLABORATION.search(clause):
            experimental_hits.update(methods)
            if _COMPUTATIONAL.search(clause) or _DATA_ANALYSIS.search(clause):
                computational_duties = True

    if experimental_hits and not computational_duties:
        return "experimental methods without computational duties"
    return None
